1)Write a python program for divison zero error
-------------------------------------------------
Program:-
=========
try:

    x=10/0

except Exception as e:

    print("an erroe occured:",str(e))
Sample input-output:-
======================
an erroe occured: division by zero

2)Write a python program to handle multiple exceptions
------------------------------------------------------
Program:-
=========
try:

    num=int(input("enter a number:"))

    result=10/num

    print("Result is:",result)

except ValueError:

    print("Error:Invalid input! please enter a valid number")

except ZeroDivisonError:
    
    print("Erroe:Divison by zero!")
Sample input-output:-
=====================
enter a number:5

Result is: 2.0
3)Write a python program to handle multiple exceptions using else clause
------------------------------------------------------------------------
Program:-
==========
try:

    num=int(input("enter a number:"))

    result=10/num

except ValueError:

    print("Error:Invalid input! please enter a valid number")

except ZeroDivisonError:

    print("Error:Divison by zero!")

else:

    print("Result:",result)
Sample input-output:-
======================
enter a number:2

Result: 5.0


4)Write a python program to perform exceptions with final block
----------------------------------------------------------------
Program:-
=========
try:

    file=open("myfile.txt","r")

except IoError:

    print("Error:unable to read the file!")
finally:
   file.close()
Sample input-output:-
======================
ERROR!
Traceback (most recent call last):

  File "<main.py>", line 2, in <module>

FileNotFoundError: 
[Errno 2] No such file or directory: 'myfile.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<main.py>", line 3, in <module>
NameError:
 name 'IoError' is not defined. Did you mean: 'IOError'?


During handling of the above exception, another exception occurred:

Traceback
 (most recent call last):
 
 File "<main.py>", line 6, 
in <module>
NameError: name 'file' is not defined



5)Write a python program to find out the given number is within range or not
-----------------------------------------------------------------------------
Program:-
==========
try:

    x=int(input("Enter a number upto 100:"))

    if x>100:

        raise ValueError(x)

except ValueError:

    print(x,"is out of allowed range")

else:

    print(x,"is within the allowed range")
Sample input-output:-
======================
Enter a number upto 100:123

123 is out of allowed range
